version: '3'
services:
  webapp:
    build: .
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/like_service
      - SPRING_DATASOURCE_USERNAME=dorian
      - SPRING_DATASOURCE_PASSWORD=dorian01

  postgres:
    image: postgres:17.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=dorian
      - POSTGRES_PASSWORD=dorian01
      - POSTGRES_DB=like_service
volumes:
  postgres_data: