spring:
  application:
    name: "LikeService"
  datasource:
    username: dorian
    password: dorian01
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5342/like_service

  flyway:
    locations: classpath:/db/migration
    schemas: public
    baseline-on-migrate: true
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none
